### ISSUE TITLE
Can't find variable: regeneratorRuntime

### ISSUE THREAD

**Issue by harri00413** [thipages/js-crud-api#1]
Started testing with this api, first try, this error comes up. 

Pops up at min.js line 168. 
Just used the HTML setup together with [api from mevdschee](https://github.com/mevdschee/php-crud-api)

**Comment by thipages** [comment]
Hi, which version of PHP-CRUD-API are you using? Currently tests are performed against v2.11.3. Can you precise the error? Thanks.

**Comment by harri00413** [comment]
Re-installed, working now. Thanks for your reaction.

**Comment by thipages** [comment]
Fine!

**Comment by enrickaliberti** [comment]
ReferenceError: regeneratorRuntime is not defined

I also have this problem, and I have everything updated

**Comment by thipages** [comment]
Hi, I just tested again, everything seems fine. Can you give me some code to read. Thanks

**Comment by wish5115** [comment]
I also encountered the same problem, all of my files are the latest version. I learned there might some errors with Wepack packaging, and then I downloaded Facebook's runtime.js to solve this problem.

Download here:
https://github.com/facebook/regenerator/blob/5703a79746fffc152600fdcef46ba9230671025a/packages/regenerator-runtime/runtime.js

Hope to resolve this error as soon as possible.
