### ISSUE TITLE
adding custom headers to requests

### ISSUE THREAD

**Issue by ghost** [thipages/js-crud-api#3]
I can't find in the documentation a way to add an API-Key to the header of the fetch request. The source is minified and I'm having an hard time trying to find the spot where inject my custom headers. 
currently I'm hijacking the the code by replacing a line:
```
//headers: o(o({}, e), t.headers)

headers: {'X-API-Key': apiKey}
```

is there a cleaner way to add custom headers?

**Comment by thipages** [comment]
Hi,
I have done the implementation but did not test it ...
You can look at the code here (in the index.js it is not minified) : https://github.com/thipages/js-crud-api/blob/42414c5e1d1a83487244c67cd6de068ff9d47cad/index.js#L21

I let you figure out. However, tell me is you have any problems, I might add a test for it.

**Comment by thipages** [comment]
the second argument "config" should be the solution
```javascript
import jscrudapi from 'js-crud-api';
const jca=jscrudapi('urlToApi.php', {
  headers : { 'X-API-Key': apiKey }
});
```

**Comment by ghost** [comment]
Thanks, I solved with:
```
const jca=jscrudapi(api_url,config={headers:{'X-API-Key':'afancyapikey'}});
```

**Comment by thipages** [comment]
there is a small mistake/typo in your code, I would write in the same spirit :
```javascript
   const config={ headers : { 'X-API-Key':'afancyapikey' }}
   const jca=jscrudapi(api_url, config);
```
